name: Stride Bridge
on:
  push:
    paths:
      - 'tasks.txt'
  workflow_dispatch:
jobs:
  run-task:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Task Directly
        run: bash tasks.txt
